import { useMemo, useState } from 'react';
import { ArrowRight, Compass, Search, Sparkles } from 'lucide-react';
import catalogRaw from '../../../content/master/thinker-catalog-v5.json';
import trailsRaw from '../../../content/master/thinker-trails-v5.json';
import mediaRaw from '../../../content/master/people-media-registry-v5.json';
import newtonProfile from '../../../content/master/newton-profile-v5.json';

type Person={id:string;name_pt:string;dates?:string;tradition?:string;domains?:string[];core_questions_pt?:string[];key_works_pt?:string[];deep_track?:boolean};
const people=catalogRaw.people as Person[];
const trails=Object.fromEntries((trailsRaw.trails||[]).map(t=>[t.person_id,t]));
const media=Object.fromEntries((mediaRaw.media||[]).map(m=>[m.person_id,m.asset_url]));

export default function ThinkerTrailsPage(){
 const [q,setQ]=useState(''); const [selected,setSelected]=useState('isaac-newton');
 const filtered=useMemo(()=>people.filter(p=>`${p.name_pt} ${p.tradition} ${(p.domains||[]).join(' ')}`.toLocaleLowerCase('pt-BR').includes(q.toLocaleLowerCase('pt-BR'))),[q]);
 const current=people.find(p=>p.id===selected) || filtered[0]; const trail=trails[current?.id];
 return <div className="mx-auto max-w-[1320px] px-4 py-6 sm:px-6 lg:px-8">
   <header className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]">
    <section className="rounded-[28px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 sm:p-8"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--accent))]"><Compass size={13}/> Trilhas de ideias</div><h1 className="mt-3 font-display text-4xl font-bold tracking-tight">Não é uma lista de filósofos. É um mapa para pensar.</h1><p className="mt-4 text-sm leading-7 text-[hsl(var(--muted-foreground))]">Filosofia, ciência, matemática, teologia, sociologia, antropologia e educação entram na mesma biblioteca, mas cada autor é apresentado pelo próprio contexto e pelas próprias obras.</p><div className="mt-5 flex flex-wrap gap-2 text-[10px] font-mono uppercase tracking-wider text-[hsl(var(--muted-foreground))]"><span className="rounded-full bg-[hsl(var(--secondary))] px-3 py-2">{people.length} pessoas catalogadas</span><span className="rounded-full bg-[hsl(var(--secondary))] px-3 py-2">{Object.keys(trails).length} trilhas profundas</span></div></section>
    <section className="rounded-[28px] bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))]"><p className="font-mono text-[10px] uppercase tracking-[.2em] opacity-60">Como estudar</p><h2 className="mt-3 text-2xl font-bold">5 → 20 → 45 minutos</h2><p className="mt-3 max-w-xl text-sm leading-6 opacity-75">Descubra a pergunta central, entenda os conceitos, abra uma obra e volte depois pelo Diário. A trilha não dá nota para o pensador; ela organiza o caminho de estudo.</p></section>
   </header>
   <div className="mt-6 grid gap-5 lg:grid-cols-[360px_1fr]">
    <aside className="rounded-[26px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-4">
      <div className="relative"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[hsl(var(--muted-foreground))]"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Newton, Platão, Weber..." className="w-full rounded-xl border border-[hsl(var(--border))] bg-transparent py-2.5 pl-8 pr-3 text-xs outline-none"/></div>
      <div className="mt-3 max-h-[650px] space-y-1 overflow-auto pr-1">{filtered.map(p=><button key={p.id} onClick={()=>setSelected(p.id)} className={`w-full rounded-2xl p-3 text-left transition ${selected===p.id?'bg-[hsl(var(--primary))] text-[hsl(var(--primary-foreground))]':'hover:bg-[hsl(var(--secondary))]'}`}><div className="flex items-center justify-between gap-3"><span className="text-sm font-bold">{p.name_pt}</span>{p.deep_track&&<Sparkles size={13} className="shrink-0"/>}</div><p className="mt-1 text-[10px] opacity-60">{p.dates} · {(p.domains||[]).slice(0,3).join(' · ')}</p></button>)}</div>
    </aside>
    <main className="rounded-[28px] border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5 sm:p-7">
      <div className="grid gap-5 md:grid-cols-[140px_1fr]">
       <div className="relative h-40 overflow-hidden rounded-3xl bg-[hsl(var(--secondary))]">{media[current?.id||'']&&<img src={media[current?.id||'']} alt={`Retrato de ${current?.name_pt}`} className="h-full w-full object-cover grayscale" onError={e=>e.currentTarget.style.display='none'}/>}</div>
       <div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[hsl(var(--accent))]">{current?.tradition||'pensamento'}</p><h2 className="mt-1 font-display text-3xl font-bold">{current?.name_pt}</h2><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{current?.dates}</p><div className="mt-4 flex flex-wrap gap-1.5">{(current?.domains||[]).map(d=><span key={d} className="rounded-full border px-2 py-1 text-[10px]">{d}</span>)}</div></div>
      </div>
      <div className="mt-6 grid gap-4 md:grid-cols-2"><section className="rounded-2xl bg-[hsl(var(--secondary)/.5)] p-4"><p className="font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">Perguntas centrais</p><ul className="mt-3 space-y-2 text-sm leading-6">{(current?.core_questions_pt||[]).slice(0,3).map(x=><li key={x}>• {x}</li>)}</ul></section><section className="rounded-2xl bg-[hsl(var(--secondary)/.5)] p-4"><p className="font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">Obras</p><div className="mt-3 space-y-2 text-sm leading-6">{(current?.key_works_pt||[]).slice(0,6).map(x=><div key={x} className="flex items-start gap-2"><ArrowRight size={13} className="mt-1 shrink-0 text-[hsl(var(--accent))]"/>{x}</div>)}</div></section></div>
      {trail ? <section className="mt-6"><div className="flex items-end justify-between gap-3"><div><p className="font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]">Trilha profunda</p><h3 className="mt-1 text-xl font-bold">{trail.title_pt}</h3></div><span className="rounded-full bg-[hsl(var(--secondary))] px-3 py-2 text-[10px] font-mono">{trail.modules.length} módulos</span></div><div className="mt-4 grid gap-2">{trail.modules.map((m:any)=><div key={m.order} className="flex items-center gap-4 rounded-2xl border border-[hsl(var(--border))] p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[hsl(var(--primary))] text-xs font-bold text-[hsl(var(--primary-foreground))]">{m.order}</span><div className="flex-1"><b className="text-sm">{m.title_pt}</b><p className="mt-1 text-xs text-[hsl(var(--muted-foreground))]">{m.duration_min} min · leitura guiada + contexto + perguntas</p></div><ArrowRight size={15} className="opacity-40"/></div>)}</div></section> : <div className="mt-6 rounded-2xl border border-dashed border-[hsl(var(--border))] p-5 text-sm text-[hsl(var(--muted-foreground))]">Este autor está no catálogo amplo e pode receber uma trilha profunda depois; a ficha já está pronta para a rotação diária.</div>}
      {current?.id==='isaac-newton' && <section className="mt-6 rounded-[26px] border border-[hsl(var(--border))] bg-[hsl(var(--secondary)/.3)] p-5"><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--muted-foreground))]"><Sparkles size={12}/> Perfil especial</div><h3 className="mt-1 text-xl font-bold">{newtonProfile.hero.headline}</h3><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">{newtonProfile.hero.subheadline}</p><div className="mt-4 grid gap-2 md:grid-cols-2">{newtonProfile.timeline.map((item:any)=><div key={item.year+item.label} className="rounded-2xl bg-[hsl(var(--card))] p-4"><p className="font-mono text-[9px] uppercase tracking-widest text-[hsl(var(--accent))]">{item.year}</p><b className="mt-1 block text-sm">{item.label}</b><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">{item.body}</p></div>)}</div></section>}
    </main>
   </div>
 </div>
}
