import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Bell, BookOpen, Check, History, Lightbulb, Quote, RotateCcw, Sparkles } from 'lucide-react';
import { getDailySet, type Question } from './content';
import InteractiveMathLab from '../labs/InteractiveMathLab';
import PhysicsFormulaLab from '../labs/PhysicsFormulaLab';
import DailyReadingCard from '../daily/DailyReadingCard';
import { recordCompleted, recordViewed } from '../final/progressStore';

function QuestionCard({q,n,onDone}:{q:Question;n:number;onDone:(id:string,correct:boolean)=>void}){
 const [selected,setSelected]=useState<number|null>(null); const answered=selected!==null; const correct=selected===q.answer;
 return <article className="panel overflow-hidden rounded-3xl"><div className="border-b border-border px-5 py-4 flex flex-wrap gap-2 items-center"><span className="font-mono text-[10px] text-muted-foreground">Q{String(n).padStart(2,'0')}</span><span className="rounded-full bg-secondary px-2 py-1 font-mono text-[9px] uppercase tracking-wider">{q.subject}</span><span className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">{q.difficulty}</span><span className="ml-auto rounded-full bg-[hsl(var(--accent)/.08)] px-2 py-1 font-mono text-[9px] text-[hsl(var(--accent))]">{q.sourceLabel}</span></div><div className="p-5 sm:p-7"><p className="eyebrow">{q.topic}</p><h2 className="mt-3 text-base font-bold leading-relaxed sm:text-lg">{q.prompt}</h2><div className="mt-6 grid gap-2">{q.options.map((op,i)=><button key={op} disabled={answered} onClick={()=>setSelected(i)} className={'flex w-full gap-3 rounded-2xl border p-4 text-left text-sm transition-all '+(answered&&i===q.answer?'border-emerald-300 bg-emerald-50':answered&&selected===i?'border-red-300 bg-red-50':'border-border hover:border-[hsl(var(--accent)/.55)] hover:bg-secondary/40')}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-secondary font-mono text-[10px] font-bold">{String.fromCharCode(65+i)}</span><span>{op}</span></button>)}</div>{answered&&<div className={'mt-5 rounded-2xl border p-4 '+(correct?'border-emerald-200 bg-emerald-50/70':'border-[hsl(var(--accent)/.25)] bg-[hsl(var(--accent)/.06)]')}><div className="flex items-center gap-2 text-xs font-bold">{correct?<Check size={15} className="text-emerald-700"/>:<RotateCcw size={15} className="text-[hsl(var(--accent))]"/>}{correct?'Resposta correta':'Repare no ponto de decisão'}</div><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{q.explanation}</p><button onClick={()=>onDone(q.id,correct)} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-[hsl(var(--primary))]">Registrar no treino <ArrowRight size={13}/></button></div>}</div></article>
}

export default function RadarDayPage(){
 const daily=useMemo(()=>getDailySet(),[]);
 useEffect(()=>{daily.questions.forEach(q=>recordViewed(`daily:${q.id}`,q.topic,q.subject))},[daily.questions]); const [done,setDone]=useState<string[]>([]); const [score,setScore]=useState(0);
 const progress=Math.round(done.length/daily.questions.length*100);
 const complete=(id:string,correct:boolean)=>{setDone(v=>v.includes(id)?v:[...v,id]);if(correct)setScore(v=>v+1);const q=daily.questions.find(x=>x.id===id);if(q)recordCompleted(`daily:${id}`,q.topic,q.subject,correct?1:0)};
 return <div className="mx-auto max-w-[1380px] space-y-7">
   <section className="relative overflow-hidden rounded-[2rem] bg-[hsl(var(--primary))] p-6 text-[hsl(var(--primary-foreground))] sm:p-9" style={{backgroundImage:"linear-gradient(90deg, hsl(var(--primary)/.97), hsl(var(--primary)/.86)), url('/assets/editorial/01_radar_de_hoje.png')",backgroundSize:'cover',backgroundPosition:'center'}}><div className="pointer-events-none absolute -right-20 -top-20 h-72 w-72 rounded-full border border-[hsl(var(--sidebar-primary)/.18)]"/><div className="relative z-10 max-w-3xl"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--sidebar-primary))]"><Sparkles size={13}/> Radar de hoje</div><h1 className="mt-3 font-display text-3xl font-bold leading-tight sm:text-5xl">Uma missão da EEAR. Uma ideia histórica. Algo que fica.</h1><p className="mt-4 text-sm leading-relaxed text-[hsl(var(--primary-foreground)/.72)]">Questões, História da Matemática, História da Física, linguagem, filosofia e método de estudo em uma única experiência diária.</p><div className="mt-6 flex flex-wrap gap-2"><span className="rounded-full bg-[hsl(var(--sidebar-primary)/.12)] px-3 py-1.5 font-mono text-[10px]">{daily.questions.length} questões</span><span className="rounded-full bg-[hsl(var(--sidebar-primary)/.12)] px-3 py-1.5 font-mono text-[10px]">4 matérias</span><span className="rounded-full bg-[hsl(var(--sidebar-primary)/.12)] px-3 py-1.5 font-mono text-[10px]">conteúdo histórico</span></div></div></section>
   <div className="grid gap-7 xl:grid-cols-[1.1fr_.9fr]">
    <section><div className="mb-4 flex items-end justify-between"><div><p className="eyebrow">Missão principal</p><h2 className="mt-1 font-display text-2xl font-bold">Treino EEAR/FAB</h2></div><span className="font-mono text-[10px] text-muted-foreground">{done.length}/{daily.questions.length} · {score} acertos</span></div><div className="mb-5 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-[hsl(var(--accent))] transition-all duration-500" style={{width:progress+'%'}}/></div><div className="space-y-4">{daily.questions.map((q,i)=><QuestionCard key={q.id} q={q} n={i+1} onDone={complete}/>)}</div></section>
    <aside className="space-y-6">
      {[daily.math,daily.physics,daily.language,daily.thinker,daily.curiosity,daily.studyTip].map((item,i)=><section key={i} className="panel overflow-hidden rounded-3xl p-5 sm:p-6"><div className="flex items-center gap-2 text-[hsl(var(--primary))]">{i===0?<History size={16}/>:i===1?<BookOpen size={16}/>:i===3?<Quote size={16}/>:<Lightbulb size={16}/>}<span className="font-mono text-[10px] uppercase tracking-wider">{item.kind==='math-history'?'História da Matemática':item.kind==='physics-history'?'História da Física':item.kind==='language'?item.subtitle:item.kind==='thinker'?'Pessoa em foco':item.kind==='curiosity'?'Curiosidade do dia':'Dica de estudo'}</span></div><h2 className="mt-3 font-display text-2xl font-bold">{item.title}</h2><p className="mt-1 text-xs text-muted-foreground">{item.subtitle}</p><p className="mt-4 text-sm leading-7">{item.text}</p></section>)}
      <DailyReadingCard day={new Date().getDate()}/>
      <section className="rounded-3xl bg-[hsl(var(--secondary)/.65)] p-5"><div className="flex items-center gap-2"><Bell size={16} className="text-[hsl(var(--accent))]"/><span className="font-mono text-[10px] uppercase tracking-wider">Notificações</span></div><p className="mt-2 text-sm font-bold">Missão, Matemática, Física, Português, Inglês, Bíblia e fechamento.</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">Os horários devem ser configuráveis, com limite diário e horário de silêncio. Push no celular depende da permissão do usuário e de um service worker.</p></section>
      <div className="flex flex-wrap gap-2"><a href="https://ingresso.eear.fab.mil.br/SOO/home/provas_anteriores.php?sigla_conc=%25" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-xs font-bold">Provas anteriores <ArrowRight size={13}/></a></div>
    </aside>
   </div>
   <InteractiveMathLab/><PhysicsFormulaLab/>
 </div>
}
