import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Mic,Search,Sparkles} from 'lucide-react';
import {Link} from 'wouter';
import index from '../../../content/v18/universal-search-index-v18.json';
import {recordViewed} from './progressStore';
type Item={id:string;title:string;type:string;subtitle?:string;tags?:string[];href?:string};
const items=index.items as Item[];
function resultHref(x: Item){
  if (x.href && ['/','/universo','/radar-do-dia','/resumos','/questoes','/descobrir','/biblioteca','/atlas','/progresso','/jogos','/anotacoes','/notificacoes','/buscar','/perfil'].includes(x.href)) return x.href;
  if (x.type==='Pessoa') return '/pensadores';
  if (x.type==='Livro') return '/biblioteca';
  if (x.type==='Lugar') return '/atlas';
  if (x.type==='Bíblia') return '/biblia';
  if (x.type==='Apócrifo') return '/apocrifos';
  if (x.type==='Cultura pop') return '/cultura-pop';
  return '/descobrir';
}
function Voice({onText}:{onText:(v:string)=>void}){const[s,setS]=useState(false);const supported=typeof window!=='undefined'&&Boolean((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition);function start(){if(!supported)return;const C=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;const r=new C();r.lang='pt-BR';r.interimResults=false;setS(true);r.onresult=(e:any)=>onText(e.results?.[0]?.[0]?.transcript??'');r.onend=()=>setS(false);r.onerror=()=>setS(false);r.start()}return <button type="button" disabled={!supported} onClick={start} className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl border border-[hsl(var(--border))] ${s?'bg-[hsl(var(--accent))] text-white':'bg-[hsl(var(--card))]'} disabled:opacity-35`} aria-label="Pesquisar por voz"><Mic size={17}/></button>}
export default function GlobalSearchPage(){const[q,setQ]=useState('');const[t,setT]=useState('Todos');const types=['Todos','Livro','Pessoa','Lugar','Bíblia','Matemática','Física','Curiosidade','Cultura pop','Apócrifo'];const r=useMemo(()=>{const z=q.trim().toLocaleLowerCase('pt-BR');return items.filter(x=>(t==='Todos'||x.type===t)&&(!z||`${x.title} ${x.subtitle??''} ${(x.tags??[]).join(' ')}`.toLocaleLowerCase('pt-BR').includes(z))).slice(0,80)},[q,t]);useEffect(()=>{document.title='Pesquisar • Radar EEAR'},[]);return <div className="mx-auto max-w-[1180px]"><header className="mb-7 rounded-[2rem] bg-[hsl(var(--primary))] p-6 text-white sm:p-9"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-[hsl(var(--sidebar-primary))]">Índice do conhecimento</p><h1 className="mt-3 font-display text-3xl font-bold sm:text-5xl">Pesquise tudo. Siga a próxima ideia.</h1><p className="mt-3 max-w-3xl text-sm leading-7 opacity-75">Uma busca para livros, pessoas, lugares, Bíblia, matemática, física, apócrifos e cultura pop.</p><div className="mt-6 flex min-w-0 items-center gap-2 rounded-xl bg-[hsl(var(--card))] px-3 text-[hsl(var(--foreground))]"><Search size={17} className="shrink-0 opacity-50"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex.: Newton, Corinto, probabilidade…" className="min-w-0 flex-1 bg-transparent py-3 text-sm outline-none" aria-label="Pesquisar"/><Voice onText={setQ}/></div></header><div className="mb-5 flex gap-2 overflow-x-auto pb-1">{types.map(x=><button key={x} onClick={()=>setT(x)} className={`min-h-11 shrink-0 rounded-full border px-4 text-xs font-bold ${t===x?'border-[hsl(var(--primary))] bg-[hsl(var(--primary))] text-white':'bg-[hsl(var(--card))]'}`}>{x}</button>)}</div><div className="grid gap-3 md:grid-cols-2">{r.map(x=><Link key={x.id} href={resultHref(x)} onClick={()=>recordViewed(x.id,x.title,x.type)} className="group panel flex min-h-24 items-center gap-4 rounded-2xl p-4"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]"><Sparkles size={17}/></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{x.title}</strong><span className="mt-1 block truncate text-xs text-[hsl(var(--muted-foreground))]">{x.type}{x.subtitle?` · ${x.subtitle}`:''}</span></span><ArrowRight size={16} className="shrink-0 opacity-45 group-hover:translate-x-1"/></Link>)}</div><p className="mt-5 text-xs text-[hsl(var(--muted-foreground))]">{items.length.toLocaleString('pt-BR')} entradas no índice v18.</p></div>}
