import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const exists=p=>fs.existsSync(path.join(root,p));
const checks=[];const failures=[];const ok=(name,value,detail='')=>{checks.push({name,ok:Boolean(value),detail});if(!value)failures.push(`${name}${detail?`: ${detail}`:''}`)};
const app=read('src/app/App.tsx');const css=read('src/index.css');const index=read('index.html');const pkg=JSON.parse(read('package.json'));const media=read('src/components/EntityMedia.tsx');
const assetsRoot=path.join(root,'public/assets');const assetSet=new Set();
function walk(dir,rel=''){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){const r=path.join(rel,ent.name);if(ent.isDirectory())walk(path.join(dir,ent.name),r);else assetSet.add('/assets/'+r.replaceAll(path.sep,'/'));}}
walk(assetsRoot);
ok('package',pkg.name==='radar-eear'&&pkg.version==='0.6.1');
ok('node24',pkg.engines?.node==='>=24 <25');
ok('pt-br',/<html[^>]*lang=["']pt-BR["']/.test(index));
ok('viewport-safe',!/maximum-scale\s*=/.test(index));
ok('auth-not-fake',!/Marina Santos|Marina Silva/.test(app));
ok('real-persistence',/bookPosition/.test(app)&&/bibleProgress/.test(app)&&/question_answered/.test(app));
ok('real-daily-links',/href=\{`\/dia\?item=\$\{d.id\}`\}/.test(app));
ok('apocrypha-link-state',app.includes('href={`/apocrifos/${encodeURIComponent(id)}`}')&&/apocrypha\.map/.test(app));
ok('topic-specific-experiences',/resolveMicroProfile/.test(app)&&/Números complexos/.test(app)&&/Trabalho e energia/.test(app)&&/Óptica/.test(app));
ok('book-cover-assets',/SmartBookCover/.test(app)&&/object-fit:contain/.test(css));
ok('portrait-fallbacks',/function SmartPortrait/.test(app)&&/wikipedia\.org/.test(app));
ok('legal-book-fallback',/function legalBookUrl/.test(app)&&/openlibrary\.org\/search/.test(app));
ok('pensadores-works',/Ver obra no Radar/.test(app)&&/Buscar edição digital/.test(app));
ok('simulation-collapsed-map',/simulation-question-map/.test(app)&&/<details className="simulation-question-map"/.test(app));
ok('google-maps-primary',/Google Maps · Atlas principal/.test(app)&&/output=embed/.test(app)&&/className="atlas-google-frame"/.test(app));
ok('atlas-width-safe-css',/atlas-google-frame\{width:100%|max-width:100%/.test(css)&&/atlas-layout\{grid-template-columns:minmax\(0,1.15fr\)/.test(css));
ok('bible-dark-reader',/\.bible-text\{background:linear-gradient/.test(css));
ok('dark-options',/\.options \.option-btn.*background:#0b151e!important/.test(css)&&/\.lesson-panel \.option-btn/.test(css));
ok('compact-thinkers',/thinker-grid/.test(css)&&/graph-node/.test(css));
ok('mobile-safe',/bottom:calc\(8px \+ env\(safe-area-inset-bottom\)\)/.test(css)&&/overflow-x:hidden/.test(css));
ok('assets',assetSet.size>=250,`found ${assetSet.size}`);
const staticRefs=[...new Set([...app].join('').matchAll(/["'](\/assets\/[A-Za-z0-9_./%-]+)["']/g))].map(m=>m[1]);const missing=staticRefs.filter(x=>!assetSet.has(x)&&!x.endsWith('/'));ok('asset-refs',missing.length===0,missing.slice(0,10).join(', '));
try{const out=execFileSync(process.execPath,['--experimental-strip-types','scripts/runtime-smoke.mjs'],{cwd:root,encoding:'utf8'});const j=JSON.parse(out.slice(out.indexOf('{')));ok('runtime-smoke',j.ok===true,JSON.stringify(j.counts));}catch(e){ok('runtime-smoke',false,e.message)}
const result={timestamp:new Date().toISOString(),summary:{passed:checks.filter(x=>x.ok).length,total:checks.length,failed:failures.length},failures,checks};fs.writeFileSync(path.join(root,'V26_6_VALIDATION.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.summary));if(failures.length)process.exit(1);
